site_name: Rust 100 问
nav:
  - 首页: index.md
  - '第一章：入门与基础': 'chapter1_basics.md'
  - '第二章：核心概念：所有权与生命周期': 'chapter2_ownership.md'
  - '第三章：复合类型与集合': 'chapter3_collections.md'
  - '第四章：高级特性': 'chapter4_advanced.md'
  - '第五章：并发与异步': 'chapter5_concurrency.md'
  - '第六章：项目与生态': 'chapter6_ecosystem.md'
  - '第七章：工程与进阶专题': 'chapter7_engineering.md'
  - 关于: about.md
theme:
    name: "material"
    logo: assets/螃蟹.png
    favicon: assets/螃蟹.png
    palette:
        primary: "deep purple"
        accent: "deep orange"
    language: "zh"

markdown_extensions:
  - admonition
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
  - assets/mermaid-init.js

