site_name: My Docs
nav:
  - Home: index.md
  - '第一章：入门与基础': 'chapter1_basics.md'
  - '第二章：核心概念：所有权与生命周期': 'chapter2_ownership.md'
  - '第三章：复合类型与集合': 'chapter3_collections.md'
  - '第四章：高级特性': 'chapter4_advanced.md'
  - About: about.md
theme:
    name: "material"
    logo: assets/仓鼠.png
    favicon: assets/仓鼠.png
    palette:
        primary: "deep purple"
        accent: "deep orange"
    language: "zh"
